---
title: "Integration Among US Banks: Rerun"
author: Abhinav Anand and John Cotter
date: '`r format(Sys.time(), "%Y/%m/%d")`' #current date

output:
  pdf_document:
    keep_tex: true

fontsize: 11pt
documentclass: article
geometry: margin = 1.5in

linkcolor: blue
urlcolor: red
citecolor: magenta

# citation_package: natbib
# bibliography: Working_Paper.bib

header-includes:
   - \linespread{1.25}
   - \usepackage{amsmath}


---


```{r setup, eval=T, message=FALSE, warning=F, include=FALSE}

library(tidyverse)
library(rmarkdown)
library(knitr)
library(moments) 
library(broom)
library(lmtest)
library(modelr)
library(plm)
library(sandwich)

knitr::opts_chunk$set(echo = F, 
                      warning = T, 
                      message = F, 
                      eval = T, 
                      include = T,
                      fig.height=5.5, 
                      fig.width=5.5,
                      fig.align = 'center'
                      )

# Preprocess, then compute then postprocess
# Includes two nested scripts 
source('Int_Banks_US_panel_estimation.R', echo = F)

# Further Tests to Do:

# Check if time fixed effects exist. If not we can justify.
# WHY does PCA capture integration? Improve Puk and Roll's answer.
# Correlation between quarterly integration and quarterly returns?
# How do factor loadings evolve? (Brennan question)
# Expl variables: number of branches, fed funds rate, factor loading signs, non-deposit financing, time fixed effects, use of derivatives, bank beta, SRISK
# Unit root test for integration?
# Fit distributions for yearly/quarterly cross-sectional integration


# Claim: Post Dodd-Frank (Q3 2010) capital quality of systemic improves...
# ... but the trend of increasing exposure to common factors doesn't



```

# Explantory Power of Eigenvectors

```{r expl_power_eig_vec}

boxplot(t(var_share_df[1:30, ]))

#barplot(expl_power_eig_med[1:30])

```

# Median US Bank Integration 

## Trends

### Tables

```{r med_US_bank_int_trend}

# Full sample period, full set of banks
knitr::kable(broom::tidy(trend_median_US_bank))

# Pre 2005, full set of banks
knitr::kable(broom::tidy(trend_median_US_bank_H1),
             caption = "Pre 2005 trend")

# Post 2005, full set of banks
knitr::kable(broom::tidy(trend_median_US_bank_H2),
             caption = "Post 2005 trend")

# Full sample period, median systemic bank
knitr::kable(broom::tidy(trend_median_US_bank_systemic),
             caption = "Systemic banks trend")

# Pre 2005, median systemic bank
knitr::kable(broom::tidy(trend_median_US_bank_systemic_H1),
             caption = "Systemic banks trend pre 2005")

# Post 2005, median systemic bank
knitr::kable(broom::tidy(trend_median_US_bank_systemic_H2),
             caption = "Systemic banks trend post 2005")

```

### Plots

```{r med_US_bank_int, fig.height= 6, fig.width=11}

# Full sample period, full bank set
plot_trend_median

# Pre 2005, full bank set
plot_trend_median_H1

# post 2005, full bank set
plot_trend_median_H2

# Full sample period, systemic bank
plot_trend_median_sys

# Pre 2005, systemic bank
plot_trend_median_sys_H1

# Post 2005, systemic bank
plot_trend_median_sys_H2

```


# Empirical Distribution of US Bank Integration

```{r emp_distr_US_bank_int}

boxplot_int_yearly

```

# Crises

```{r crises}

knitr::kable(broom::tidy(trend_median_US_bank_crisis))

```

# Panel Estimation

```{r panel_est}

# Full model
knitr::kable(broom::tidy(panel_est_full$coefficients), 
             caption = "All banks")

# Systemic banks
knitr::kable(broom::tidy(panel_est_sys$coefficients), 
             caption = "Systemic banks")

# Pre 2005
knitr::kable(broom::tidy(panel_est_H1$coefficients), 
             caption = "Pre 2005")

# Post 2005
knitr::kable(broom::tidy(panel_est_H2$coefficients), 
             caption = "Post 2005")

```
